### ISSUE TITLE
Trojan virus.

### ISSUE THREAD

**Issue by Cursees** [ptedeschi/NFT.net#1]
Why is there a trojan in this file? 
![image](https://user-images.githubusercontent.com/89230972/134079601-4d4e5160-8b06-4794-9b16-a3c6a9a8085c.png)

**Comment by ptedeschi** [comment]
I will investigate it. 
Which tool accused it?

**Comment by Cursees** [comment]
Virustotal.com fam, ty

**Comment by ptedeschi** [comment]
I was able to reproduce the issue @Cursees.
I created a new WinForms project and then published it. virustotal.com found nothing.
But, when I published the same code using the option "Trim unused assemblies"...

![image](https://user-images.githubusercontent.com/6684508/134112224-3f598e3c-e5a7-4031-9f86-ffa4dbc1e670.png)

... virustotal.com identified it as Trojan/Generic.ASMalwS.3487958.

Thank you for raising this concern.
I'm going to try to raise this with Microsoft, but we need to understand that this feature is in the preview stage.

What I am doing from my side is creating a new release version without this option.
The file size will be a little bigger, but it will give you the confidence to use the application after checking it with virustotal.com.

![image](https://user-images.githubusercontent.com/6684508/134113557-0dd5d189-8b7c-46a0-9e17-3205d0c6097d.png)

Please, look for the [v1.1.1](https://github.com/ptedeschi/NFT.net/releases/download/v1.1.1/NFT.net.zip).

I am waiting for your feedback so we can close this issue.

**Comment by ptedeschi** [comment]
Issue raised with Microsoft
https://github.com/dotnet/aspnetcore/issues/36786
