### ISSUE TITLE
Rarity of each item

### ISSUE THREAD

**Issue by philicomus** [ptedeschi/NFT.net#10]
Great tool - I'm currently using it to produce a 1000-nft collection.

Probably a beginner question but given my metadata, how do I get a rarity score for each individual item?

**Comment by ptedeschi** [comment]
Thanks @philicomus!
Currently, you can set the weight of each trait to choose from, but you can't see a rarity rating in the end.
I'll leave this issue open because it seems useful to try to implement this functionality.
Thanks for the feedback!

**Comment by philicomus** [comment]
Great, many thanks!

**Comment by ptedeschi** [comment]
Closing this question since @philicomus contributed with a solution that has already been merged to master!
