### ISSUE TITLE
Use Decimal Weights?

### ISSUE THREAD

**Issue by Tominium** [ptedeschi/NFT.net#2]
I am having trouble using decimal weights on images. If I do "+2.5" it is not putting the weight as 2.5%. Are decimal weights possible?

**Comment by ptedeschi** [comment]
Hi Katy! Thanks for using the tool.
Only integers are currently supported. I'll add this to the readme.
Don't forget to use the 'Check Trait Weights' window to analise your weights.
And please, share your NFT with us so we can help publicize it.
Cheers!

**Comment by ptedeschi** [comment]
Readme was updated to mention that only integers numbers are supported for setting weights.
Closing this issue.

**Comment by ihorbond** [comment]
@ptedeschi came across this project on ProductHunt, awesome to see .NET community working on NFTs as well! I would suggest to use the actual % in the file name, I think this would make it much easier to people to understand, cheers!
