### ISSUE TITLE
isn't seed supported ? 

### ISSUE THREAD

**Issue by novaknole** [ptedeschi/NFT.net#3]
Hi and thanks for such a great project.

1. Isn't there any package like this in javascript ? mainly, I like the weights idea so much.
2. With the weights property and how you do `randomization`, can't we set `seed` so that it's reproducible ? i think it's pretty necessary in NFT. if so, could you let me know where ?

**Comment by novaknole** [comment]
Ah, for 2nd question, I found the answer - you can pass in a constructor. all good.

**Comment by ptedeschi** [comment]
Hi. Glad you liked it!
About the Randomizer library, it's a third party. You can check it's code here https://github.com/BlueRaja/Weighted-Item-Randomizer-for-C-Sharp. And you're right, there is a DynamicWeightedRandomizer overload that lets you pass a seed. It's in my roadmap to allow changing this information from the main UI. Wait for the next releases. Cheers!

**Comment by Kshatriykrish** [comment]
Hi
