### ISSUE TITLE
Attempted to run on Windows 10 on Parallels on Mac M1 Pro

### ISSUE THREAD

**Issue by gianni-dalerta** [ptedeschi/NFT.net#5]
Great project! I know this may not have been tested on win 10, much less on a virtual computer on mac. But when running the app. I get "An unkown error has happened. Parameter is not valid."

Going to attempt to run on an older version of windows.

**Comment by ptedeschi** [comment]
Thanks @gianni-dalerta!

The project was built and tested on Windows 10, so I think there's something related to Parallels.
I'm going to apply some changes related to the file and directory path and I will let you know so you can test.

Cheers!

**Comment by Kshatriykrish** [comment]
Happy New year

**Comment by ptedeschi** [comment]
@gianni-dalerta , can you please test this version https://github.com/ptedeschi/NFT.net/releases/download/v1.2.1/NFT.net.zip ?
If the error persists, it should now show more details on the screen, so I ask you to take a screenshot and paste it here. Thanks!

**Comment by ptedeschi** [comment]
Closing the issue as the reporter did not provide details about the submitted fix.
If the error persists, please open a new issue!
Cheers!
